name: spotify_flutter
description: A custom multiplatform spotify client made using flutter.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  http: 0.13.3

  flutter_web_auth: 0.3.0

  flutter_dotenv: 3.1.0

  fluttertoast: 8.0.6

  flutter_swiper: 1.1.6

  spotify_sdk: 2.1.0

  superellipse_shape: 0.1.6

  path_provider: 2.0.1

  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/spotify_icon.png

  fonts:
    - family: Nunito
      fonts:
        - asset: fonts/Nunito-Bold.ttf
        - asset: fonts/Nunito-Regular.ttf
        - asset: fonts/Nunito-Light.ttf